# Generated by Django 6.0.6 on 2026-06-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ciudades/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('estrellas', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='hoteles.ciudad')),
            ],
        ),
    ]
